object Dep {
    const val buildTools = "30.0.3"
    const val kotlin = "1.8.0"
    const val coreKtx = "1.3.1"
    const val lifecycleKtx = "2.4.0"
    const val appCompat = "1.2.0"
    const val recyclerView = "1.1.0"
    const val lifeCycleCompiler = "2.2.0"
    const val gson = "2.8.5"
    const val junit = "4.12"
    const val androidxJunitExt = "1.1.2"
    const val espresso = "3.3.0"
    const val gms_google_services = "4.3.15"
    const val exoPlayer = "2.9.5"
    const val hilt = "2.44.2"
    const val hilt_androidx_compiler = "2.44"
    const val glide = "4.12.0"
    const val androidx_appCompat = "1.4.1"
    const val constraintLayout = "2.0.4"
    const val lifecycle_viewmodel_ktx = "2.5.0"
    const val lifecycleExt = "2.2.0"
    const val lifecycle_runtime_ktx = "2.5.0"
    const val lifecycle_common_java8 = "2.5.0"
    const val work_runtime_ktx = "2.7.1"
    const val activity_ktx = "1.5.0"
    const val fragment_ktx = "1.5.0"
    const val androidx_annotation = "1.4.0"
    const val retrofit = "2.9.0"
    const val retrofit_converter_gson = "2.9.0"
    const val okhttp = "4.9.1"
    const val logging_interceptor = "4.9.1"
    const val androidx_recyclerview = "1.2.1"
    const val material = "1.6.1"
    const val lottie = "3.7.0"
    const val flexbox = "3.0.0"

}